/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/8.0.20
 * Generated at: 2021-04-01 02:46:34 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;
import general.FormReplacer;
import model.*;
import controller.*;
import ctrl.*;
import java.util.*;
import model.Admin;
import model.User;
import ctrl.SvlUlrl;
import ctrl.*;

public final class menuUpdate_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports {

String[] menuName = { "メニューメンテ", "予約確認", "ログアウト" };
String[] menuLink = { SvlUlrl.MenuMaintenanceSvl, "/ideal/controller/AdminReserveListSvl",  "/ideal/controller/UserLogoffSvl" };
  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  static {
    _jspx_dependants = new java.util.HashMap<java.lang.String,java.lang.Long>(1);
    _jspx_dependants.put("/adminHeader.jsp", Long.valueOf(1617235598841L));
  }

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("javax.servlet");
    _jspx_imports_packages.add("controller");
    _jspx_imports_packages.add("java.util");
    _jspx_imports_packages.add("javax.servlet.http");
    _jspx_imports_packages.add("ctrl");
    _jspx_imports_packages.add("model");
    _jspx_imports_packages.add("javax.servlet.jsp");
    _jspx_imports_classes = new java.util.HashSet<>();
    _jspx_imports_classes.add("model.Admin");
    _jspx_imports_classes.add("model.User");
    _jspx_imports_classes.add("general.FormReplacer");
    _jspx_imports_classes.add("ctrl.SvlUlrl");
  }

  private javax.el.ExpressionFactory _el_expressionfactory;
  private org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public void _jspInit() {
    _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
    _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

final java.lang.String _jspx_method = request.getMethod();
if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method) && !javax.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET POST or HEAD");
return;
}

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html; charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n");
      out.write("<head>\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ideal/css/button.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ideal/css/bgBlur.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ideal/css/form.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ideal/css/header.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ideal/css/bg.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ideal/css/footer.css\" />\r\n");
      out.write("<link rel=\"stylesheet\" href=\"/ideal/css/title.css\" />\r\n");
      out.write("<meta http-equiv=\"Content-Type\" content=\"text/html; charset=UTF-8\" />\r\n");
      out.write("<meta name=\"viewport\" content=\"width=device-width,initial-scale=1\" />\r\n");
      out.write("<title>Update Menu</title>\r\n");
      out.write("<script type=\"text/javascript\">\r\n");
      out.write("\tfunction check() {\r\n");
      out.write("\t\tif (document.menuInsert.menuName.value == \"\") {\r\n");
      out.write("\t\t\twindow.alert(\"メニュー名が未入力です。\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (document.menuInsert.price.value == \"\") {\r\n");
      out.write("\t\t\twindow.alert(\"価格が未入力です。\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t} else if (priceRegexCheck(document.menuInsert.price.value)) {\r\n");
      out.write("\t\t\twindow.alert(\"価格は数字で入力してください。\");\r\n");
      out.write("\t\t\treturn false;\r\n");
      out.write("\t\t}\r\n");
      out.write("\t\treturn true;\r\n");
      out.write("\t}\r\n");
      out.write("\r\n");
      out.write("\tfunction priceRegexCheck(pass) {\r\n");
      out.write("\t\tconst\r\n");
      out.write("\t\tregex = new RegExp('^[0-9]+$');\r\n");
      out.write("\t\treturn !regex.test(pass);\r\n");
      out.write("\t}\r\n");
      out.write("</script>\r\n");
      out.write("\r\n");
      out.write("<title>メニュー更新画面</title>\r\n");
      out.write("\r\n");
      out.write("</head>\r\n");
      out.write("<body>\r\n");
      out.write("\t");

		int typeID;
		try {
			typeID = Integer.parseInt(request.getParameter("typeID"));
		} catch (NumberFormatException e) {
			typeID = 100;
		}
	
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t<!--↓oneMenuはMenuOperationSvlで格納  -->\r\n");
      out.write("\t");

		Menu oneMenu = (Menu) request.getAttribute("oneMenu");
	
      out.write("\r\n");
      out.write("\t<!--↓mTypeはMenuMaintenanceSvlで格納  -->\r\n");
      out.write("\t");

		ArrayList<MenuType> mType = (ArrayList<MenuType>) request
				.getAttribute("mType");
	
      out.write("\r\n");
      out.write("\t<div style=\"min-height: 100vh; position: relative;\">\r\n");
      out.write("\t\t");
      out.write("<?xml version=\"1.0\" encoding=\"UTF-8\" ?>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\r\n");
      out.write("\r\n");
      out.write("<noscript>\r\n");
      out.write("\t<META http-equiv=\"Refresh\" content=\"0;noScriptError.jsp\" />\r\n");
      out.write("</noscript>\r\n");

	Admin amd = (Admin) session.getAttribute(AdminVar.adminInfo);

      out.write('\r');
      out.write('\n');
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("<div id=\"header-left\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- ロゴをクリックすることでホームへ移動 -->\r\n");
      out.write("\t<img id=\"header-logo\" src=\"/ideal/img/logo.svg\" alt=\"Homeへ戻る\" />\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("<div id=\"header\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- PS向けのメニュー -->\r\n");
      out.write("\t<div id=\"header-right\">\r\n");
      out.write("\t\t");

			for (int i = 0; i < menuName.length; i++) {
		
      out.write("\r\n");
      out.write("\t\t<a class=\"header-button\" style=\"width:25%\" href=\"");
      out.print(menuLink[i]);
      out.write('"');
      out.write('>');
      out.print(menuName[i]);
      out.write("</a>\r\n");
      out.write("\t\t");

			}
		
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</div>\r\n");
      out.write("<div class=\"burgerKing bgBlur\">\r\n");
      out.write("\r\n");
      out.write("\t<!-- ロゴをクリックすることでホームへ移動 -->\r\n");
      out.write("\t<img id=\"header-logo\" src=\"/ideal/img/logo.svg\" alt=\"Homeへ戻る\" />\r\n");
      out.write("\r\n");
      out.write("</div>\r\n");
      out.write("<input type=\"checkbox\" id=\"menu-btn-check\"> <label\r\n");
      out.write("\tfor=\"menu-btn-check\" class=\"menu-btn\"><span class=\"menu-btn\"></span></label>\r\n");
      out.write("\t<div class=\"menu-content\">\r\n");
      out.write("\t\t<!-- スマホ向けのメニュー -->\r\n");
      out.write("\t\t<ul class=\"menu-content-ul\">\r\n");
      out.write("\t\t\t");

				for (int i = 0; i < menuName.length; i++) {
			
      out.write("\r\n");
      out.write("\t\t\t<li class=\"menu-content-ul-li\"><a href=\"");
      out.print(menuLink[i]);
      out.write('"');
      out.write('>');
      out.print(menuName[i]);
      out.write("</a>\r\n");
      out.write("\t\t\t</li>\r\n");
      out.write("\t\t\t");

				}
			
      out.write("\r\n");
      out.write("\t\t</ul>\r\n");
      out.write("\t</div>\r\n");
      out.write("</input>");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<div class=\"titleSticky\">\r\n");
      out.write("\t\t\t<div class=\"titleInnerDiv\">\r\n");
      out.write("\t\t\t\t<h1 class=\"redBack\">メニューの更新</h1>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</div>\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "idealException.jsp", out, false);
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t<center>\r\n");
      out.write("\t\t\t<div class=\"tableDiv bgBlur\">\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t<form id=\"menuInsert\" name=\"menuInsert\"\r\n");
      out.write("\t\t\t\t\taction=\"/ideal/controller/MenuOperationSvl\" method=\"post\"\r\n");
      out.write("\t\t\t\t\tonsubmit=\"return check();\">\r\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"formDivInner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"titleDiv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tableDef\">メニュー名</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"messageDiv\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"inputDef\" id=\"menuName\" type=\"text\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"menuName\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tvalue=\"");
      out.print(FormReplacer.fmtNull(oneMenu.getMenuName()));
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"messageDiv\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"formDivInner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"titleDiv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tableDef\">価格</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"messageDiv\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<input class=\"inputDef\" id=\"price\" type=\"text\" name=\"price\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tsize=\"6\" value=\"");
      out.print(oneMenu.getPrice());
      out.write("\" />\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"messageDiv\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"formDivInner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"titleDiv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tableDef\">オーダー可</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"messageDiv\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div\r\n");
      out.write("\t\t\t\t\t\t\t\tstyle=\"width: 26em; display: flex; justify-content: space-around; color: white;\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"orderFlg\" value=\"1\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(FormReplacer.checkeder(oneMenu.getOrderFlg(), 1));
      out.write(" />可\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<input type=\"radio\" name=\"orderFlg\" value=\"0\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(FormReplacer.checkeder(oneMenu.getOrderFlg(), 0));
      out.write(" />不可\r\n");
      out.write("\t\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"messageDiv\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"formDivInner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"titleDiv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tableDef\">メニューの分類</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"messageDiv\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<select class=\"inputDef\" id=\"typeID\" name=\"typeID\">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										for (MenuType mt : mType) {
											if (mt.getTypeID() != 100) {
												String selected = "";
												if (typeID == mt.getTypeID()) {
													selected = "selected";
												} else {
													selected = "";
												}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t\t<option value=\"");
      out.print(mt.getTypeID());
      out.write('"');
      out.write(' ');
      out.print(selected);
      out.write(">\r\n");
      out.write("\t\t\t\t\t\t\t\t\t\t");
      out.print(mt.getTypeName());
      out.write("</option>\r\n");
      out.write("\t\t\t\t\t\t\t\t\t");

										}
										}
									
      out.write("\r\n");
      out.write("\t\t\t\t\t\t\t\t</select>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div class=\"messageDiv\"></div>\r\n");
      out.write("\t\t\t\t\t<div class=\"formDiv\">\r\n");
      out.write("\t\t\t\t\t\t<div class=\"formDivInner\">\r\n");
      out.write("\t\t\t\t\t\t\t<div class=\"titleDiv\">\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"tableDef\">コメント</div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<div class=\"messageDiv\"></div>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t\t<div>\r\n");
      out.write("\t\t\t\t\t\t\t\t<textarea class=\"inputDef\" style=\"height: 200px; resize: none;\"\r\n");
      out.write("\t\t\t\t\t\t\t\t\tname=\"detail\">");
      out.print(FormReplacer.fmtNull(oneMenu.getDetail()) );
      out.write("</textarea>\r\n");
      out.write("\t\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<div style=\"display: flex; justify-content: center;\">\r\n");
      out.write("\t\t\t\t\t\t<input class=\"button enterButton\" type=\"submit\" value=\"登録\" />\r\n");
      out.write("\t\t\t\t\t</div>\r\n");
      out.write("\t\t\t\t\t<input type=\"hidden\" name=\"mode\"\r\n");
      out.write("\t\t\t\t\t\tvalue=\"");
      out.print(MenuOperationSvl.UPDATE);
      out.write("\" /> <input type=\"hidden\"\r\n");
      out.write("\t\t\t\t\t\tname=\"menuID\" value=\"");
      out.print(oneMenu.getMenuId());
      out.write("\" /> <input\r\n");
      out.write("\t\t\t\t\t\ttype=\"hidden\" name=\"typeID\" value=\"");
      out.print(oneMenu.getTypeId());
      out.write("\" />\r\n");
      out.write("\t\t\t\t</form>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"height: 50px\">\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"margin-top: 3em; display: flex; justify-content: center;\">\r\n");
      out.write("\t\t\t\t<a class=\"button enterButton\" href=\"");
      out.print(SvlUlrl.MenuMaintenanceSvl);
      out.write("\">メニューメンテナンスに戻る</a>\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t\t<div style=\"height: 50px\">\r\n");
      out.write("\t\t\t\t<br />\r\n");
      out.write("\t\t\t</div>\r\n");
      out.write("\t\t</center>\r\n");
      out.write("\r\n");
      out.write("\r\n");
      out.write("\t\t");
      org.apache.jasper.runtime.JspRuntimeLibrary.include(request, response, "/footer.jsp", out, false);
      out.write("\r\n");
      out.write("\t</div>\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
